version: 2

project_name: t-f

before:
  hooks:
    - go mod tidy

builds:
  - id: t-f
    main: ./cmd/t-f
    binary: t-f
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X t-f/internal/version.Version={{.Version}} -X t-f/internal/version.Commit={{.Commit}} -X t-f/internal/version.Date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "^refactor:"
      - "Merge branch"
      - "Merge pull request"